/*
 * Auto-generated shader code for IPlugEffect
 * Source: IPlugEffect.frag
 * Generated by: Scripts/convert-shader.sh
 *
 * To regenerate:
 *   cd iPlug2
 *   ./Scripts/convert-shader.sh Examples/IPlugEffect/IPlugEffect.frag \
 *       Examples/IPlugEffect all
 */

#pragma once

// ============================================================================
// SkSL shader for Skia backend
// ============================================================================
#if defined(IGRAPHICS_SKIA)

static const char* kIPlugEffectShader = R"(
uniform float uTime;
uniform float2 uResolution;
uniform float2 uMouse;
uniform float2 uMouseButtons;

half4 main(float2 fragCoord) {
  float2 uv = fragCoord / uResolution;
  return half4(uv.x, uv.y, sin(uTime) * 0.5 + 0.5, 1.0);
}
)";

#endif // IGRAPHICS_SKIA

// ============================================================================
// GLSL ES shader for NanoVG GLES2 backend (WebGL 1.0)
// ============================================================================
#if defined(IGRAPHICS_NANOVG) && defined(IGRAPHICS_GLES2)

static const char* kIPlugEffectShader = R"(
#ifdef GL_ES
precision mediump float;
#endif
uniform float uTime;
uniform vec2 uResolution;
uniform vec2 uMouse;
uniform vec2 uMouseButtons;
varying vec2 vTexCoord;

void main()
{
    vec2 uv = gl_FragCoord.xy / uResolution;
    gl_FragColor = vec4(uv.x, uv.y, (sin(uTime) * 0.5) + 0.5, 1.0);
}
)";

#endif // IGRAPHICS_NANOVG && IGRAPHICS_GLES2

// ============================================================================
// GLSL shader for NanoVG GL3/GLES3 backend (UBO version)
// ============================================================================
#if defined(IGRAPHICS_NANOVG) && defined(IGRAPHICS_GL) && !defined(IGRAPHICS_GLES2)

static const char* kIPlugEffectShader = R"(#version 330

layout(std140) uniform Uniforms
{
    float uTime;
    vec2 uResolution;
    vec2 uMouse;
    vec2 uMouseButtons;
} _19;

layout(location = 0) out vec4 FragColor;

void main()
{
    vec2 uv = gl_FragCoord.xy / _19.uResolution;
    FragColor = vec4(uv.x, uv.y, (sin(_19.uTime) * 0.5) + 0.5, 1.0);
}
)";

#endif // IGRAPHICS_NANOVG && IGRAPHICS_GL && !IGRAPHICS_GLES2

// ============================================================================
// Metal shader for NanoVG Metal backend
// ============================================================================
#if defined(IGRAPHICS_NANOVG) && defined(IGRAPHICS_METAL)

static const char* kIPlugEffectVertexFunc = "shaderVertexFunc";
static const char* kIPlugEffectFragmentFunc = "shaderFragmentFunc";

static const char* kIPlugEffectMetalShader = R"(
#include <metal_stdlib>
#include <simd/simd.h>
using namespace metal;

struct Uniforms {
  float uTime;
  float _pad0;
  float2 uResolution;
  float2 uMouse;
  float2 uMouseButtons;
};

struct VertexOut {
  float4 position [[position]];
  float2 texCoord;
};

vertex VertexOut shaderVertexFunc(uint vertexID [[vertex_id]],
                                   constant float2* vertices [[buffer(0)]]) {
  VertexOut out;
  out.position = float4(vertices[vertexID], 0.0, 1.0);
  out.texCoord = vertices[vertexID] * 0.5 + 0.5;
  return out;
}

fragment half4 shaderFragmentFunc(VertexOut in [[stage_in]],
                                   constant Uniforms& uniforms [[buffer(0)]]) {
  float2 uv = in.texCoord;
  uv.y = 1.0 - uv.y;
  half3 col = half3(uv.x, uv.y, 0.5 + 0.5 * sin(uniforms.uTime));
  return half4(col, 1.0);
}
)";

#endif // IGRAPHICS_NANOVG && IGRAPHICS_METAL
