#  ==============================================================================
#
#  This file is part of the iPlug 2 library. Copyright (C) the iPlug 2 developers.
#
#  See LICENSE.txt for more info.
#
#  ==============================================================================

# GenerateResources.cmake
# Generates resource files (plist, main.rc, XIB) from config.h at configure time.
#
# Usage:
#   iplug_generate_resources(<project_name> <project_dir>)
#
# This function:
# 1. Parses config.h to extract plugin metadata
# 2. Generates plist files for macOS plugin formats (APP, VST3, AU, CLAP)
# 3. Generates Windows resource files (resource.h, main.rc)
# 4. Generates macOS XIB file for standalone app menu
#
# Generated files are placed in ${CMAKE_CURRENT_BINARY_DIR}/generated_resources/
# and the path is stored in IPLUG_GENERATED_RESOURCES_DIR.

include_guard(GLOBAL)

include(${CMAKE_CURRENT_LIST_DIR}/ParseConfig.cmake)

# Template directory
set(IPLUG_TEMPLATES_DIR "${CMAKE_CURRENT_LIST_DIR}/templates" CACHE INTERNAL "iPlug2 resource templates directory")

# Default macOS deployment target
if(NOT DEFINED MACOS_DEPLOYMENT_TARGET)
  set(MACOS_DEPLOYMENT_TARGET "10.13.0")
endif()

function(iplug_generate_resources project_name project_dir)
  # Parse config.h
  iplug_parse_config(${project_dir})

  # Set output directory
  set(GEN_DIR "${CMAKE_CURRENT_BINARY_DIR}/generated_resources")
  file(MAKE_DIRECTORY ${GEN_DIR})

  # Export for use by other CMake files
  set(IPLUG_GENERATED_RESOURCES_DIR ${GEN_DIR} PARENT_SCOPE)
  set(IPLUG_GENERATED_RESOURCES_DIR ${GEN_DIR} CACHE INTERNAL "Generated resources directory")

  message(STATUS "[iPlug2] Generating resources for ${project_name} in ${GEN_DIR}")

  # Generate plist files for macOS
  if(APPLE)
    _iplug_generate_plist_files(${project_name} ${GEN_DIR})
    _iplug_generate_xib(${project_name} ${GEN_DIR})
  endif()

  # Generate Windows resource files
  _iplug_generate_rc_files(${project_name} ${GEN_DIR})

  # Generate SWELL files for macOS APP target
  if(APPLE)
    _iplug_generate_swell_files(${GEN_DIR})
  endif()

endfunction()

# Internal function to generate all plist files
function(_iplug_generate_plist_files project_name output_dir)
  # Formats and their template names
  set(PLIST_FORMATS APP VST3 AU CLAP)

  foreach(format ${PLIST_FORMATS})
    set(TEMPLATE "${IPLUG_TEMPLATES_DIR}/Info-${format}.plist.in")
    set(OUTPUT "${output_dir}/${project_name}-${format}-Info.plist")

    # For AU, we need the proper naming convention
    if(format STREQUAL "AU")
      set(OUTPUT "${output_dir}/${project_name}-AU-Info.plist")
    elseif(format STREQUAL "APP")
      set(OUTPUT "${output_dir}/${project_name}-macOS-Info.plist")
    else()
      set(OUTPUT "${output_dir}/${project_name}-${format}-Info.plist")
    endif()

    if(EXISTS ${TEMPLATE})
      configure_file(${TEMPLATE} ${OUTPUT} @ONLY)
      message(STATUS "[iPlug2]   Generated: ${OUTPUT}")
    else()
      message(WARNING "[iPlug2] Template not found: ${TEMPLATE}")
    endif()
  endforeach()
endfunction()

# Internal function to generate XIB file for macOS app
function(_iplug_generate_xib project_name output_dir)
  set(XIB_TEMPLATE "${IPLUG_TEMPLATES_DIR}/MainMenu.xib.in")
  set(XIB_OUTPUT "${output_dir}/${project_name}-macOS-MainMenu.xib")

  if(EXISTS ${XIB_TEMPLATE})
    configure_file(${XIB_TEMPLATE} ${XIB_OUTPUT} @ONLY)
    message(STATUS "[iPlug2]   Generated: ${XIB_OUTPUT}")
  else()
    message(WARNING "[iPlug2] XIB template not found: ${XIB_TEMPLATE}")
  endif()
endfunction()

# Internal function to generate Windows resource files
function(_iplug_generate_rc_files project_name output_dir)
  # Generate resource.h (static content)
  set(RESOURCE_H_TEMPLATE "${IPLUG_TEMPLATES_DIR}/resource.h.in")
  set(RESOURCE_H_OUTPUT "${output_dir}/resource.h")

  if(EXISTS ${RESOURCE_H_TEMPLATE})
    configure_file(${RESOURCE_H_TEMPLATE} ${RESOURCE_H_OUTPUT} @ONLY)
    message(STATUS "[iPlug2]   Generated: ${RESOURCE_H_OUTPUT}")
  else()
    # If no template exists, generate a default resource.h
    _iplug_generate_default_resource_h(${output_dir})
  endif()

  # Generate main.rc
  set(RC_TEMPLATE "${IPLUG_TEMPLATES_DIR}/main.rc.in")
  set(RC_OUTPUT "${output_dir}/main.rc")

  if(EXISTS ${RC_TEMPLATE})
    configure_file(${RC_TEMPLATE} ${RC_OUTPUT} @ONLY)
    message(STATUS "[iPlug2]   Generated: ${RC_OUTPUT}")
  else()
    # If no template exists, generate a minimal main.rc
    _iplug_generate_default_main_rc(${project_name} ${output_dir})
  endif()
endfunction()

# Generate default resource.h if template doesn't exist
function(_iplug_generate_default_resource_h output_dir)
  set(CONTENT "//{{NO_DEPENDENCIES}}
// Generated by iPlug2 CMake build system

#define IDR_ACCELERATOR1                40000
#define IDD_DIALOG_MAIN                 40001
#define IDD_DIALOG_PREF                 40002
#define IDI_ICON1                       40003
#define IDR_MENU1                       40004
#define ID_ABOUT                        40005
#define ID_PREFERENCES                  40006
#define ID_QUIT                         40007
#define ID_HELP                         40008
#define IDC_COMBO_AUDIO_DRIVER          40009
#define IDC_COMBO_AUDIO_IN_DEV          40010
#define IDC_COMBO_AUDIO_OUT_DEV         40011
#define IDC_COMBO_AUDIO_BUF_SIZE        40012
#define IDC_COMBO_AUDIO_SR              40013
#define IDC_COMBO_AUDIO_IN_L            40014
#define IDC_COMBO_AUDIO_IN_R            40015
#define IDC_COMBO_AUDIO_OUT_R           40016
#define IDC_COMBO_AUDIO_OUT_L           40017
#define IDC_COMBO_MIDI_IN_DEV           40018
#define IDC_COMBO_MIDI_OUT_DEV          40019
#define IDC_COMBO_MIDI_IN_CHAN          40020
#define IDC_COMBO_MIDI_OUT_CHAN         40021
#define IDC_BUTTON_OS_DEV_SETTINGS      40022
#define IDC_CB_MONO_INPUT               40023
#define IDAPPLY                         40024
#define ID_LIVE_EDIT                    40025
#define ID_SHOW_DRAWN                   40026
#define ID_SHOW_FPS                     40027
#define ID_SHOW_BOUNDS                  40028

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
")
  file(WRITE "${output_dir}/resource.h" "${CONTENT}")
  message(STATUS "[iPlug2]   Generated default: ${output_dir}/resource.h")
endfunction()

# Generate minimal main.rc if template doesn't exist
function(_iplug_generate_default_main_rc project_name output_dir)
  # Use parent scope variables from iplug_parse_config
  set(CONTENT "// Generated by iPlug2 CMake build system
#include \"resource.h\"

#define APSTUDIO_READONLY_SYMBOLS
#include \"winres.h\"
#undef APSTUDIO_READONLY_SYMBOLS

#if !defined(AFX_RESOURCE_DLL) || defined(AFX_TARG_ENG)
LANGUAGE LANG_ENGLISH, SUBLANG_ENGLISH_UK
#pragma code_page(1252)

/////////////////////////////////////////////////////////////////////////////
// Dialog
//

IDD_DIALOG_PREF DIALOG 0, 0, 223, 309
STYLE DS_SETFONT | DS_MODALFRAME | DS_3DLOOK | DS_FIXEDSYS | DS_CENTER | WS_POPUP | WS_VISIBLE | WS_CAPTION | WS_SYSMENU
CAPTION \"Preferences\"
FONT 8, \"MS Sans Serif\"
BEGIN
    DEFPUSHBUTTON   \"OK\",IDOK,110,285,50,14
    PUSHBUTTON      \"Apply\",IDAPPLY,54,285,50,14
    PUSHBUTTON      \"Cancel\",IDCANCEL,166,285,50,14
    COMBOBOX        IDC_COMBO_AUDIO_DRIVER,20,35,100,100,CBS_DROPDOWNLIST | CBS_HASSTRINGS
    LTEXT           \"Driver Type\",IDC_STATIC,22,25,38,8
    COMBOBOX        IDC_COMBO_AUDIO_IN_DEV,20,65,100,200,CBS_DROPDOWNLIST | CBS_HASSTRINGS
    LTEXT           \"Input Device\",IDC_STATIC,20,55,42,8
    COMBOBOX        IDC_COMBO_AUDIO_OUT_DEV,20,95,100,200,CBS_DROPDOWNLIST | CBS_HASSTRINGS
    LTEXT           \"Output Device\",IDC_STATIC,20,85,47,8
    COMBOBOX        IDC_COMBO_AUDIO_BUF_SIZE,135,35,65,100,CBS_DROPDOWNLIST | CBS_HASSTRINGS
    LTEXT           \"Buffer Size\",IDC_STATIC,137,25,46,8
    COMBOBOX        IDC_COMBO_AUDIO_SR,135,95,65,200,CBS_DROPDOWNLIST | CBS_HASSTRINGS
    LTEXT           \"Sampling Rate\",IDC_STATIC,135,85,47,8
    GROUPBOX        \"Audio Device Settings\",IDC_STATIC,5,10,210,170
    PUSHBUTTON      \"Config...\",IDC_BUTTON_OS_DEV_SETTINGS,135,155,65,14
    COMBOBOX        IDC_COMBO_AUDIO_IN_L,20,125,40,200,CBS_DROPDOWNLIST | CBS_HASSTRINGS
    LTEXT           \"Input 1 (L)\",IDC_STATIC,20,115,33,8
    COMBOBOX        IDC_COMBO_AUDIO_IN_R,65,126,40,200,CBS_DROPDOWNLIST | CBS_HASSTRINGS
    LTEXT           \"Input 2 (R)\",IDC_STATIC,65,115,34,8
    COMBOBOX        IDC_COMBO_AUDIO_OUT_L,20,155,40,200,CBS_DROPDOWNLIST | CBS_HASSTRINGS
    LTEXT           \"Output 1 (L)\",IDC_STATIC,20,145,38,8
    COMBOBOX        IDC_COMBO_AUDIO_OUT_R,65,155,40,200,CBS_DROPDOWNLIST | CBS_HASSTRINGS
    LTEXT           \"Output 2 (R)\",IDC_STATIC,65,145,40,8
    GROUPBOX        \"MIDI Device Settings\",IDC_STATIC,5,190,210,85
    COMBOBOX        IDC_COMBO_MIDI_OUT_DEV,15,250,100,200,CBS_DROPDOWNLIST | CBS_HASSTRINGS
    LTEXT           \"Output Device\",IDC_STATIC,15,240,47,8
    COMBOBOX        IDC_COMBO_MIDI_IN_DEV,15,220,100,200,CBS_DROPDOWNLIST | CBS_HASSTRINGS
    LTEXT           \"Input Device\",IDC_STATIC,15,210,42,8
    LTEXT           \"Input Channel\",IDC_STATIC,125,210,45,8
    COMBOBOX        IDC_COMBO_MIDI_IN_CHAN,125,220,50,200,CBS_DROPDOWNLIST | CBS_HASSTRINGS
    LTEXT           \"Output Channel\",IDC_STATIC,125,240,50,8
    COMBOBOX        IDC_COMBO_MIDI_OUT_CHAN,125,250,50,200,CBS_DROPDOWNLIST | CBS_HASSTRINGS
END

IDD_DIALOG_MAIN DIALOG 0, 0, 300, 300
STYLE DS_SETFONT | DS_MODALFRAME | DS_CENTER | WS_MINIMIZEBOX | WS_POPUP | WS_CAPTION | WS_SYSMENU
CAPTION \"${PLUG_NAME}\"
MENU IDR_MENU1
FONT 8, \"MS Sans Serif\"
BEGIN
END

/////////////////////////////////////////////////////////////////////////////
// Menu
//

IDR_MENU1 MENU
BEGIN
    POPUP \"&File\"
    BEGIN
        MENUITEM \"&Preferences...\\tCtrl+,\",     ID_PREFERENCES
        MENUITEM \"&Quit\",                       ID_QUIT
    END
    POPUP \"&Debug\"
    BEGIN
        MENUITEM \"&Live Edit Mode\\tCtrl+E\",     ID_LIVE_EDIT
        MENUITEM \"&Show Control Bounds\\tCtrl+B\", ID_SHOW_BOUNDS
        MENUITEM \"&Show Drawn Area\\tCtrl+D\",    ID_SHOW_DRAWN
        MENUITEM \"&Show FPS\\tCtrl+F\",           ID_SHOW_FPS
    END
    POPUP \"&Help\"
    BEGIN
        MENUITEM \"&About\",                      ID_ABOUT
        MENUITEM \"&Read Manual\",                ID_HELP
    END
END

/////////////////////////////////////////////////////////////////////////////
// Accelerator
//

IDR_ACCELERATOR1 ACCELERATORS
BEGIN
    VK_OEM_COMMA,   ID_PREFERENCES,         VIRTKEY, CONTROL, NOINVERT
    \"B\",            ID_SHOW_BOUNDS,         VIRTKEY, CONTROL, NOINVERT
    \"D\",            ID_SHOW_DRAWN,          VIRTKEY, CONTROL, NOINVERT
    \"F\",            ID_SHOW_FPS,            VIRTKEY, CONTROL, NOINVERT
    \"E\",            ID_LIVE_EDIT,           VIRTKEY, CONTROL, NOINVERT
END

/////////////////////////////////////////////////////////////////////////////
// Version
//

VS_VERSION_INFO VERSIONINFO
FILEVERSION ${VERSION_MAJOR},${VERSION_MINOR},${VERSION_BUGFIX},0
PRODUCTVERSION ${VERSION_MAJOR},${VERSION_MINOR},${VERSION_BUGFIX},0
 FILEFLAGSMASK 0x3fL
#ifdef _DEBUG
 FILEFLAGS 0x1L
#else
 FILEFLAGS 0x0L
#endif
 FILEOS 0x40004L
 FILETYPE 0x1L
 FILESUBTYPE 0x0L
BEGIN
    BLOCK \"StringFileInfo\"
    BEGIN
        BLOCK \"040004e4\"
        BEGIN
            VALUE \"FileVersion\", \"${FULL_VER_STR}\"
            VALUE \"ProductVersion\", \"${FULL_VER_STR}\"
            VALUE \"FileDescription\", \"${PLUG_NAME}\"
            VALUE \"InternalName\", \"${PLUG_NAME}\"
            VALUE \"ProductName\", \"${PLUG_NAME}\"
            VALUE \"CompanyName\", \"${PLUG_MFR}\"
            VALUE \"LegalCopyright\", \"${PLUG_COPYRIGHT_STR}\"
            VALUE \"LegalTrademarks\", \"VST is a trademark of Steinberg Media Technologies GmbH, Audio Unit is a trademark of Apple, Inc.\"
        END
    END
    BLOCK \"VarFileInfo\"
    BEGIN
        VALUE \"Translation\", 0x400, 1252
    END
END

#endif

#ifndef APSTUDIO_INVOKED
#include \"..\\config.h\"
#endif
")
  file(WRITE "${output_dir}/main.rc" "${CONTENT}")
  message(STATUS "[iPlug2]   Generated default: ${output_dir}/main.rc")
endfunction()

# Internal function to generate SWELL files from main.rc for macOS APP
function(_iplug_generate_swell_files output_dir)
  # Create resources subdirectory (for #include "resources/main.rc_mac_dlg")
  set(RESOURCES_SUBDIR "${output_dir}/resources")
  file(MAKE_DIRECTORY ${RESOURCES_SUBDIR})

  # Find swell_resgen.pl
  set(SWELL_RESGEN "${IPLUG2_DIR}/WDL/swell/swell_resgen.pl")
  set(MAIN_RC "${output_dir}/main.rc")

  if(EXISTS ${SWELL_RESGEN} AND EXISTS ${MAIN_RC})
    # Run swell_resgen.pl to generate main.rc_mac_dlg and main.rc_mac_menu
    execute_process(
      COMMAND perl ${SWELL_RESGEN} ${MAIN_RC}
      WORKING_DIRECTORY ${output_dir}
      RESULT_VARIABLE SWELL_RESULT
      OUTPUT_VARIABLE SWELL_OUTPUT
      ERROR_VARIABLE SWELL_ERROR
    )

    if(SWELL_RESULT EQUAL 0)
      # swell_resgen.pl creates files in the same directory as main.rc
      # Move them to the resources subdirectory
      if(EXISTS "${output_dir}/main.rc_mac_dlg")
        file(RENAME "${output_dir}/main.rc_mac_dlg" "${RESOURCES_SUBDIR}/main.rc_mac_dlg")
        message(STATUS "[iPlug2]   Generated: ${RESOURCES_SUBDIR}/main.rc_mac_dlg")
      endif()
      if(EXISTS "${output_dir}/main.rc_mac_menu")
        file(RENAME "${output_dir}/main.rc_mac_menu" "${RESOURCES_SUBDIR}/main.rc_mac_menu")
        message(STATUS "[iPlug2]   Generated: ${RESOURCES_SUBDIR}/main.rc_mac_menu")
      endif()
    else()
      message(WARNING "[iPlug2] swell_resgen.pl failed: ${SWELL_ERROR}")
    endif()
  else()
    if(NOT EXISTS ${SWELL_RESGEN})
      message(WARNING "[iPlug2] swell_resgen.pl not found at ${SWELL_RESGEN}")
    endif()
  endif()
endfunction()
