target 'App' do
    use_frameworks!
    pod 'AudioKit', '~> 4.0'
    platform :ios, '11.0'
    project 'projects/IPlugSwift-iOS.xcodeproj'
    workspace 'IPlugSwift'
  end

target 'AUv3' do
    use_frameworks!
    pod 'AudioKit', '~> 4.0'
    platform :ios, '11.0'
    project 'projects/IPlugSwift-iOS.xcodeproj'
    workspace 'IPlugSwift'
end