name: 'Build Windows Project'
description: 'Build an iPlug2 project for Windows using MSBuild'

inputs:
  project:
    description: 'Project name (e.g., IPlugEffect)'
    required: true
  path:
    description: 'Path to project folder (e.g., Examples or Tests)'
    required: true
  graphics:
    description: 'Graphics backend (NANOVG or SKIA)'
    required: true
    default: 'NANOVG'
  build_vst3:
    description: 'Build VST3 format'
    required: false
    default: 'true'
  build_app:
    description: 'Build standalone app'
    required: false
    default: 'true'
  configuration:
    description: 'Build configuration (Release or Debug)'
    required: false
    default: 'Release'

runs:
  using: 'composite'
  steps:
    - name: Configure graphics backend
      shell: bash
      run: |
        if [ "${{ inputs.graphics }}" = "SKIA" ]; then
          cd ./${{ inputs.path }}/${{ inputs.project }}/config
          sed -i 's/IGRAPHICS_NANOVG;IGRAPHICS_GL2/IGRAPHICS_SKIA;IGRAPHICS_GL2/' ${{ inputs.project }}-win.props
        fi

    - name: Build VST3
      if: ${{ inputs.build_vst3 == 'true' }}
      shell: pwsh
      run: |
        msbuild "${{ inputs.path }}/${{ inputs.project }}/${{ inputs.project }}.sln" `
          /t:${{ inputs.project }}-vst3 `
          /p:Configuration=${{ inputs.configuration }} `
          /p:Platform=x64 `
          /m

    - name: Build APP
      if: ${{ inputs.build_app == 'true' }}
      shell: pwsh
      run: |
        msbuild "${{ inputs.path }}/${{ inputs.project }}/${{ inputs.project }}.sln" `
          /t:${{ inputs.project }}-app `
          /p:Configuration=${{ inputs.configuration }} `
          /p:Platform=x64 `
          /m

    - name: Organize artifacts
      shell: bash
      run: |
        mkdir -p artifacts/VST3/${{ inputs.project }}_${{ inputs.graphics }}
        mkdir -p artifacts/APP/${{ inputs.project }}_${{ inputs.graphics }}

        cd ${{ inputs.path }}/${{ inputs.project }}/build-win/

        if [ -d "${{ inputs.project }}.vst3" ]; then
          cp -r "${{ inputs.project }}.vst3" ../../../artifacts/VST3/${{ inputs.project }}_${{ inputs.graphics }}/
        fi

        if [ -f "${{ inputs.project }}_x64.exe" ]; then
          cp "${{ inputs.project }}_x64.exe" ../../../artifacts/APP/${{ inputs.project }}_${{ inputs.graphics }}/
        fi

        # Copy PDB files for debugging
        if [ -d "pdbs" ]; then
          cp pdbs/*.pdb ../../../artifacts/VST3/${{ inputs.project }}_${{ inputs.graphics }}/ 2>/dev/null || true
          cp pdbs/*.pdb ../../../artifacts/APP/${{ inputs.project }}_${{ inputs.graphics }}/ 2>/dev/null || true
        fi
