<<includeIntrinsic>>

#define FAUSTFLOAT sample

#include "IPlugFaust.h"

/* BEGIN AUTO GENERATED BY THE FAUST COMPILER ... */

<<includeclass>>

/* ... END AUTO GENERATED BY THE FAUST COMPILER  */

class FaustGen : public IPlugFaust
{
public:
	FaustGen(IPlugBase& plug, const char* name, const char* inputDSPFile = 0, int nVoices = 1, int rate = 1,
						const char* outputCPPFile = 0, const char* drawPath = 0, const char* libraryPath = DEFAULT_FAUST_LIBRARY_PATH)
	: IPlugFaust(plug, name, nVoices)
	{
	}

	void Init(int maxNInputs = 0, int maxNOutputs = 0) override
	{
		mDSP = new FAUSTCLASS();
		mDSP->buildUserInterface(this);
		BuildParameterMap();
		mInitialized = true;
	}
};

