#include "TestArcControl.h"
#include "TestDirBrowseControl.h"
#include "TestGradientControl.h"
#include "TestMultiPathControl.h"
#include "TestPolyControl.h"
#include "TestTextControl.h"
#include "TestAnimationControl.h"
#include "TestDrawContextControl.h"
