jobs:
- job: PUBLISH_DOCUMENTATION
  condition: eq(variables.publish_docs, true)
  
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self

  - bash: |
      apt-get install doxygen
      apt-get install doxygen-doc
      apt-get install doxygen-gui
      apt-get install graphviz

      cd ./Documentation
      doxygen Doxyfile
      echo "" > html/.nojekyll