#ifndef CAIRO_FEATURES_H
#define CAIRO_FEATURES_H

//#include <GL/glew.h>
//#define CAIRO_HAS_GL_SURFACE 1

#define CAIRO_HAS_IMAGE_SURFACE 1
#define CAIRO_HAS_USER_FONT 1

#define CAIRO_HAS_PNG_FUNCTIONS 1

#define CAIRO_HAS_SVG_SURFACE 0
#define CAIRO_HAS_PDF_SURFACE 0
#define CAIRO_HAS_PS_SURFACE 0

#define CAIRO_HAS_WIN32_SURFACE 1
#define CAIRO_HAS_WIN32_FONT 1

#define CAIRO_HAS_FT_FONT 0

#define CAIRO_HAS_WGL_FUNCTIONS 1
#endif
