<<includeIntrinsic>>

#define FAUSTFLOAT sample

#include "IPlugFaust.h"

/* BEGIN AUTO GENERATED BY THE FAUST COMPILER ... */

<<includeclass>>

/* ... END AUTO GENERATED BY THE FAUST COMPILER  */

class FaustGen : public IPlugFaust
{
public:
	FaustGen(const char* name,
           const char* inputDSPFile = 0,
           const char* outputCPPFile = 0,
           const char* archFile = 0,
           const char* drawPath = 0,
           const char* libraryPath = DEFAULT_FAUST_LIBRARY_PATH,
           int nVoices = 1)
	: IPlugFaust(name, nVoices)
	{
	}

	void Init(const char* str, int maxNInputs = 0, int maxNOutputs = 0) override
	{
		mDSP = new FAUSTCLASS();
		mDSP->buildUserInterface(this);
	}
};

